import type { CareModule, ContentPack, DiagnosisTopic, MedicationTopic } from '../types/content'

const diagnoses: DiagnosisTopic[] = [
  {
    id: 'depression',
    slug: 'major-depression',
    name: '憂鬱症',
    coreSummary: '憂鬱症不是單純心情差，而是情緒、睡眠、專注與體力一起卡住，通常需要連續幾週到數月的治療。',
    commonSymptoms: ['情緒低落', '興趣下降', '睡眠改變', '疲倦無力', '注意力變差'],
    courseExpectation: '規律治療後多半先看到睡眠、食慾或焦慮下降，再慢慢恢復情緒與功能；完整穩定通常比想像中更需要時間。',
    redFlags: ['出現自傷或自殺想法', '完全無法起床或進食', '突然極度激動、混亂或失眠惡化'],
    myths: ['不是意志力差', '症狀好一點也不建議自行停藥', '憂鬱常會同時表現在身體不舒服'],
    treatmentFocus: ['先穩住睡眠與生活節奏', '規律服藥比頻繁換藥更重要', '心理治療可幫助降低復發'],
    selfCareTips: ['每天固定起床時間', '把一天拆成可完成的小任務', '把情緒變化告訴家人或醫療團隊'],
    relatedMedicationIds: ['antidepressant-ssri', 'antidepressant-snri', 'antidepressant-other', 'hypnotic-bzd'],
    relatedModuleIds: ['activity-activation', 'sleep-rhythm', 'therapy-engagement', 'medication-adherence'],
  },
  {
    id: 'anxiety',
    slug: 'anxiety-disorder',
    name: '焦慮症',
    coreSummary: '焦慮症是身體長時間維持警戒的狀態，常出現擔心停不下來、胸悶心悸、肌肉緊繃與睡不好。',
    commonSymptoms: ['過度擔心', '心悸胸悶', '肌肉緊繃', '腸胃不適', '難以放鬆'],
    courseExpectation: '治療通常是把身體警戒慢慢降下來，不是一次完全消失；藥物、放鬆練習與壓力辨識常要一起進行。',
    redFlags: ['恐慌發作明顯變多', '焦慮到無法工作上學', '合併明顯憂鬱或自傷念頭'],
    myths: ['焦慮不是想太多而已', '呼吸訓練需要平常反覆練習', '短效鎮定藥通常不是唯一長期治療'],
    treatmentFocus: ['先建立可重複使用的降速工具', '藥物與心理治療常需並行', '避免把所有身體不適都解讀成危險'],
    selfCareTips: ['先把呼吸放慢而不是急著壓掉感覺', '減少咖啡因與能量飲', '記錄最常引發焦慮的情境'],
    relatedMedicationIds: ['antidepressant-ssri', 'antidepressant-snri', 'hypnotic-bzd', 'hypnotic-supportive'],
    relatedModuleIds: ['panic-grounding', 'stress-regulation', 'therapy-engagement', 'substance-reduction'],
  },
  {
    id: 'insomnia',
    slug: 'insomnia',
    name: '失眠症',
    coreSummary: '失眠的治療重點不是單靠加藥，而是重新建立固定睡眠訊號，讓大腦知道什麼時候該睡、該醒。',
    commonSymptoms: ['入睡困難', '夜間易醒', '太早醒', '白天疲倦', '對睡眠過度焦慮'],
    courseExpectation: '睡眠改善通常先從固定起床、減少補眠與重整晚間節奏開始，短期藥物只是輔助，不是全部。',
    redFlags: ['連續多日幾乎完全睡不著', '出現躁期表現', '白天嗜睡已影響安全'],
    myths: ['躺久不等於有休息到', '酒精不能當安眠方法', '失眠治療不一定要長期吃藥'],
    treatmentFocus: ['固定起床點比固定睡著時間更重要', '減少躺床清醒時間', '必要時短期用藥，但同步調整睡眠習慣'],
    selfCareTips: ['中午後減少茶咖啡與尼古丁', '睡不著時先離床做安靜活動', '白天保留固定活動量與日照'],
    relatedMedicationIds: ['hypnotic-bzd', 'hypnotic-zdrug', 'hypnotic-supportive', 'antidepressant-other'],
    relatedModuleIds: ['sleep-rhythm', 'stress-regulation', 'substance-reduction', 'screen-boundaries'],
  },
  {
    id: 'bipolar',
    slug: 'bipolar-disorder',
    name: '雙相情緒障礙',
    coreSummary: '雙相情緒障礙會在憂鬱期與躁期或輕躁期之間波動，重點不是只治某一次發作，而是穩定整個情緒週期。',
    commonSymptoms: ['情緒起伏大', '睡眠需求下降', '衝動消費', '語速變快', '憂鬱與高昂交替'],
    courseExpectation: '治療常需要長期追蹤與規律用藥；越早辨識躁期前兆，越能降低住院與功能受損風險。',
    redFlags: ['幾乎不睡仍精力旺盛', '衝動行為快速增加', '出現幻聽妄想或明顯判斷力下降'],
    myths: ['情緒特別好不一定代表恢復', '只在低潮時吃藥通常不夠', '家屬觀察到的前兆很重要'],
    treatmentFocus: ['規律使用情緒穩定藥是核心', '睡眠長短常是最早警訊', '和家屬一起建立前兆清單'],
    selfCareTips: ['固定睡眠節律', '避免熬夜、酒精與突然停藥', '事先約定躁期時的求助方式'],
    relatedMedicationIds: [
      'mood-lithium',
      'mood-valproate',
      'mood-lamotrigine',
      'antipsychotic-done',
      'antipsychotic-pine',
      'antipsychotic-piprazole',
    ],
    relatedModuleIds: ['relapse-signatures', 'sleep-rhythm', 'family-communication', 'medication-adherence'],
  },
  {
    id: 'schizophrenia',
    slug: 'schizophrenia-spectrum',
    name: '思覺失調症',
    coreSummary: '思覺失調症會影響感知、思考與現實感，治療目標是降低復發、維持功能，並讓病人與家屬更早辨識警訊。',
    commonSymptoms: ['幻聽', '妄想', '思考跳躍', '動機下降', '社交退縮'],
    courseExpectation: '急性症狀常能靠藥物先壓下來，但功能重建和生活穩定通常需要更長期的支持與合作。',
    redFlags: ['命令型幻聽', '拒食拒水或明顯混亂', '停藥後迅速惡化'],
    myths: ['症狀改善後仍可能復發', '副作用多半有機會調整', '家屬支持會直接影響穩定度'],
    treatmentFocus: ['規律抗精神病藥可降低復發', '及早處理副作用能提高持續度', '生活節奏與社會支持同樣重要'],
    selfCareTips: ['固定作息與回診', '把復發前兆寫下來', '讓主要照顧者知道求助窗口'],
    relatedMedicationIds: ['antipsychotic-done', 'antipsychotic-pine', 'antipsychotic-piprazole'],
    relatedModuleIds: ['family-communication', 'medication-adherence', 'relapse-signatures', 'return-to-work'],
  },
  {
    id: 'adhd',
    slug: 'adhd',
    name: 'ADHD',
    coreSummary: 'ADHD 會影響注意力、衝動控制與時間管理，治療是在減少生活摩擦，幫助病人更穩定發揮功能。',
    commonSymptoms: ['容易分心', '拖延', '衝動插話', '忘東忘西', '任務切換困難'],
    courseExpectation: '合適藥物配合外部提醒與任務拆解，常能在數天到數週內看到專注與執行功能改善。',
    redFlags: ['衝動行為造成安全風險', '學業或工作功能快速下降', '合併情緒失控或物質使用'],
    myths: ['不是懶散或不夠努力', '成年人也可能有 ADHD', '吃藥不是唯一方法，但常能明顯降低生活摩擦'],
    treatmentFocus: ['藥物幫助專注，策略幫助維持', '安排外部提醒與任務拆解', '追蹤食慾、睡眠與心悸變化'],
    selfCareTips: ['把任務拆成 10 到 20 分鐘', '用外部提醒取代只靠記憶', '預先規畫開始點與收尾點'],
    relatedMedicationIds: ['adhd-stimulant', 'adhd-atomoxetine', 'adhd-alpha2'],
    relatedModuleIds: ['task-structuring', 'return-to-work', 'sleep-rhythm', 'therapy-engagement'],
  },
]

const medications: MedicationTopic[] = [
  {
    id: 'antidepressant-ssri',
    slug: 'medication-antidepressant-ssri',
    name: 'SSRI 類抗憂鬱劑',
    groupId: 'antidepressants',
    groupLabel: '抗憂鬱劑',
    groupDescription: '先選抗憂鬱劑，再區分 SSRI、SNRI 或其他機轉。',
    classLabel: 'Sertraline / Escitalopram / Fluoxetine 等',
    shortSummary: '多用於憂鬱與焦慮，起效較慢但穩定，是常見的一線選擇。',
    patientIntro: 'SSRI 類常用於憂鬱、焦慮、恐慌與強迫相關症狀，通常需要規律服用 2 到 4 週後才會慢慢感受到核心效果。',
    indications: ['憂鬱症', '焦慮症', '恐慌症狀', '強迫症狀'],
    onset: '多半先看到焦躁、睡眠或身體不適慢慢下降，完整情緒改善通常需要 2 到 4 週以上。',
    commonSideEffects: ['噁心', '腸胃不適', '頭暈', '初期睡不好或想睡', '性功能副作用'],
    seriousSideEffects: ['躁期惡化', '嚴重坐立不安', '自傷想法明顯增加', '高燒、肌肉僵硬或意識改變'],
    practicalTips: ['固定同一時間服藥', '前兩週先觀察噁心、睡眠與焦躁變化', '症狀穩定後仍需和醫師討論維持期'],
    missedDoseAdvice: '若距離下次服藥還久可補吃，若太接近下次時間就跳過，不要一次補兩倍。',
    discontinuationAdvice: '不要突然停藥，以免出現頭暈、麻電感、焦躁與睡眠惡化，需和醫師討論逐步調整。',
    whenToCall: ['出現自傷念頭', '嚴重噁心嘔吐無法進食', '疑似躁期或情緒過度亢奮'],
    faq: [
      { question: '為什麼吃了幾天還沒感覺？', answer: '這類藥物多半需要數週累積效果，先看是否規律服藥與副作用是否可調整。' },
      { question: '症狀好了就可以停嗎？', answer: '通常還要維持一段時間，過早停藥會提高復發機會。' },
    ],
    relatedDiagnosisIds: ['depression', 'anxiety'],
  },
  {
    id: 'antidepressant-snri',
    slug: 'medication-antidepressant-snri',
    name: 'SNRI 類抗憂鬱劑',
    groupId: 'antidepressants',
    groupLabel: '抗憂鬱劑',
    groupDescription: '先選抗憂鬱劑，再區分 SSRI、SNRI 或其他機轉。',
    classLabel: 'Venlafaxine / Duloxetine / Desvenlafaxine 等',
    shortSummary: '用於憂鬱與焦慮，也常兼顧疼痛或身體不適；起效需要時間，初期要留意血壓與焦躁。',
    patientIntro: 'SNRI 類同時作用在血清素與正腎上腺素，對憂鬱、焦慮與部分慢性疼痛相關症狀都可能有幫助。',
    indications: ['憂鬱症', '焦慮症', '疼痛合併情緒症狀', '動力低落'],
    onset: '效果通常在 2 到 4 週慢慢累積，部分人初期可能先感到口乾、噁心或緊張。',
    commonSideEffects: ['噁心', '口乾', '流汗增加', '焦躁', '血壓偏高'],
    seriousSideEffects: ['血壓明顯升高', '躁期惡化', '自傷念頭增加', '高燒或意識改變'],
    practicalTips: ['若容易噁心可和食物一起服用', '回診時主動回報血壓、焦躁與睡眠變化', '不要自行快速停藥，戒斷感受常比 SSRI 明顯'],
    missedDoseAdvice: '若距離下次很近就直接跳過，不要補雙倍，特別是長效劑型更不要自行重複補服。',
    discontinuationAdvice: 'SNRI 戒斷不適可能較明顯，若要停藥通常需要更漸進的減量方式。',
    whenToCall: ['血壓明顯升高或頭痛厲害', '焦躁坐立不安很明顯', '出現躁期或自傷念頭'],
    faq: [
      { question: '和 SSRI 差在哪？', answer: 'SNRI 多了一條正腎上腺素路徑，有些人對動力、疼痛或倦怠改善更有感。' },
      { question: '血壓需要特別注意嗎？', answer: '部分藥物和劑量確實需要監測血壓，尤其原本就有高血壓的人。' },
    ],
    relatedDiagnosisIds: ['depression', 'anxiety'],
  },
  {
    id: 'antidepressant-other',
    slug: 'medication-antidepressant-other',
    name: '其他抗憂鬱劑',
    groupId: 'antidepressants',
    groupLabel: '抗憂鬱劑',
    groupDescription: '先選抗憂鬱劑，再區分 SSRI、SNRI 或其他機轉。',
    classLabel: 'Mirtazapine / Bupropion / Trazodone 等',
    shortSummary: '不同藥物差異很大，常依失眠、食慾、倦怠或性副作用需求來選。',
    patientIntro: '這一群藥物機轉差異較大，有些偏助眠、增進食慾，有些偏提升動力，因此更需要依個別副作用與目標來選擇。',
    indications: ['憂鬱症', '失眠合併情緒症狀', '食慾下降', '動力不足'],
    onset: '有些助眠或食慾效果會比較早出現，但核心情緒改善仍常需 2 到 4 週以上。',
    commonSideEffects: ['嗜睡', '食慾增加', '頭暈', '口乾', '焦躁或心悸'],
    seriousSideEffects: ['躁期惡化', '癲癇風險增加', '自傷想法增加', '高燒或意識改變'],
    practicalTips: ['回診時清楚說明想改善的是睡眠、食慾還是白天動力', '有些藥適合睡前，有些不適合太晚吃', '副作用差異大，換藥時更要和醫師確認過渡方式'],
    missedDoseAdvice: '依藥物特性處理，若不確定屬於助眠型還是白天型，先不要自行補雙倍。',
    discontinuationAdvice: '因為藥物差異大，停藥與換藥更要按個別計畫進行，不建議自行快速抽掉。',
    whenToCall: ['白天昏沉或心悸明顯', '情緒突然惡化', '出現躁期或不尋常行為'],
    faq: [
      { question: '為什麼我吃的是助眠型抗憂鬱劑？', answer: '有些抗憂鬱劑在低劑量時較偏鎮靜，會用在失眠合併憂鬱或焦慮的情況。' },
      { question: '是不是代表我比較嚴重？', answer: '不一定，多半是根據你的症狀組合和副作用考量做選擇。' },
    ],
    relatedDiagnosisIds: ['depression', 'insomnia'],
  },
  {
    id: 'hypnotic-bzd',
    slug: 'medication-hypnotic-bzd',
    name: 'BZD 類鎮靜安眠藥',
    groupId: 'hypnotics',
    groupLabel: '抗焦慮與鎮靜安眠藥',
    groupDescription: '先選鎮靜安眠藥，再分 BZD、Z-drug 或其他輔助藥物。',
    classLabel: 'Lorazepam / Alprazolam / Clonazepam 等',
    shortSummary: '效果快，適合短期緩解焦慮或失眠，但要注意嗜睡、跌倒與依賴風險。',
    patientIntro: 'BZD 類多在 15 到 60 分鐘內就會有放鬆或想睡的感覺，常用於急性焦慮、恐慌或短期失眠。',
    indications: ['急性焦慮', '恐慌發作', '短期失眠', '急性坐立不安'],
    onset: '服用後通常很快有感，因此更需要注意服藥時間、劑量與隔天殘留效果。',
    commonSideEffects: ['嗜睡', '頭暈', '反應變慢', '注意力下降', '隔天宿醉感'],
    seriousSideEffects: ['跌倒', '呼吸抑制', '和酒精併用危險', '突然停用後戒斷不適'],
    practicalTips: ['吃完後避免開車與高風險操作', '連續用一段時間後不要突然停', '回診時誠實說明實際使用頻率'],
    missedDoseAdvice: '若已接近起床時間就不要補吃，以免白天過度嗜睡；若是依需要使用，也不要為了補吃而額外加量。',
    discontinuationAdvice: '連續使用一段時間後需要逐步減量，突然停藥可能引發反彈失眠、焦躁或手抖。',
    whenToCall: ['白天太昏沉影響安全', '跌倒或意識混亂', '需要越吃越多才有感'],
    faq: [
      { question: '會不會上癮？', answer: '長期連續使用確實會增加依賴風險，因此通常會和醫師一起規劃使用長度。' },
      { question: '可以配酒嗎？', answer: '不建議，酒精會放大鎮靜效果並提高危險。' },
    ],
    relatedDiagnosisIds: ['anxiety', 'insomnia', 'depression'],
  },
  {
    id: 'hypnotic-zdrug',
    slug: 'medication-hypnotic-zdrug',
    name: 'Z-drug 類安眠藥',
    groupId: 'hypnotics',
    groupLabel: '抗焦慮與鎮靜安眠藥',
    groupDescription: '先選鎮靜安眠藥，再分 BZD、Z-drug 或其他輔助藥物。',
    classLabel: 'Zolpidem / Zopiclone 等',
    shortSummary: '多用在入睡困難，起效快，但仍可能夢遊、失憶或隔天殘留。',
    patientIntro: 'Z-drug 類多用在入睡困難，通常要在準備上床時再服用，並確保服後可以留出足夠睡眠時間。',
    indications: ['入睡困難', '短期失眠', '夜間難以關機'],
    onset: '通常 15 到 30 分鐘內起效，若服後還繼續滑手機、工作或外出，風險會上升。',
    commonSideEffects: ['嗜睡', '頭暈', '失憶片段', '夢境鮮明', '隔天恍神'],
    seriousSideEffects: ['夢遊或睡眠中異常行為', '跌倒', '與酒精併用危險', '反彈失眠'],
    practicalTips: ['確認可以直接上床再服藥', '服藥後不要再開車外出', '若常有半夜醒來補吃習慣，要回診重新評估'],
    missedDoseAdvice: '若已不是準備睡覺的時段就不要補吃，半夜補吃前也要確認距離起床還有足夠時間。',
    discontinuationAdvice: '不要因為當晚睡不好就自行加量，也不要連續使用後突然抽掉，否則常出現反彈失眠。',
    whenToCall: ['夢遊、講話或做事自己不記得', '隔天昏沉影響工作安全', '睡眠品質越來越靠加量維持'],
    faq: [
      { question: '是不是比 BZD 安全很多？', answer: '雖然特性不同，但仍有跌倒、失憶與依賴風險，不能當成完全無風險。' },
      { question: '半夜醒來可以補吃嗎？', answer: '要看距離起床時間與個別藥物，最好先和醫師確認。' },
    ],
    relatedDiagnosisIds: ['insomnia'],
  },
  {
    id: 'hypnotic-supportive',
    slug: 'medication-hypnotic-supportive',
    name: '其他輔助鎮靜藥',
    groupId: 'hypnotics',
    groupLabel: '抗焦慮與鎮靜安眠藥',
    groupDescription: '先選鎮靜安眠藥，再分 BZD、Z-drug 或其他輔助藥物。',
    classLabel: 'Quetiapine 低劑量 / Hydroxyzine / Propranolol 等',
    shortSummary: '不是典型安眠藥，但會依焦慮、心悸、躁動或失眠型態作為輔助。',
    patientIntro: '這一群藥物用途差異大，有些是降低身體焦躁，有些偏幫助入睡或穩定晚間躁動，重點是依個別症狀選擇。',
    indications: ['焦慮合併心悸', '晚間躁動', '失眠輔助', '藥物過渡期症狀'],
    onset: '有些藥當天就有效，有些只是作為短期過渡與搭配治療的一部分。',
    commonSideEffects: ['嗜睡', '頭暈', '口乾', '血壓偏低', '反應變慢'],
    seriousSideEffects: ['跌倒', '心律不整', '明顯姿勢性頭暈', '白天功能受損'],
    practicalTips: ['這類藥物差異很大，回診時要講清楚實際是哪一顆', '若白天昏沉明顯，提早回報醫師', '不要把朋友適合的藥直接套用到自己身上'],
    missedDoseAdvice: '依個別藥物處理，若不確定是規律服用還是依需要使用，先不要自行補倍數。',
    discontinuationAdvice: '雖然有些看起來像輔助藥，但仍可能需要漸進調整，不建議自己忽停忽吃。',
    whenToCall: ['白天太昏沉或頭暈', '心悸或昏厥感', '症狀越來越需要加量才壓得住'],
    faq: [
      { question: '這顆不是安眠藥，為什麼睡前吃？', answer: '有些藥雖然原本不是安眠藥，但會利用它的鎮靜特性幫助過渡期症狀。' },
      { question: '是不是代表病情比較重？', answer: '不一定，多半是根據你的症狀組合與副作用考量在做搭配。' },
    ],
    relatedDiagnosisIds: ['anxiety', 'insomnia'],
  },
  {
    id: 'antipsychotic-done',
    slug: 'medication-antipsychotic-done',
    name: '抗精神病藥：-done 類',
    groupId: 'antipsychotics',
    groupLabel: '抗精神病藥',
    groupDescription: '先選抗精神病藥，再區分 -done、-pine、-piprazole 類等常見群組。',
    classLabel: 'Risperidone / Paliperidone / Lurasidone / Ziprasidone 等',
    shortSummary: '常用於思覺失調與躁期，常見要留意僵硬、坐立不安、泌乳素或姿勢性頭暈。',
    patientIntro: '-done 類是常見的抗精神病藥群組，對幻聽、妄想、躁動或情緒失控都可能有幫助，但副作用型態和 -pine 類不太一樣。',
    indications: ['思覺失調症', '躁期', '精神病性症狀', '情緒失控合併妄想幻覺'],
    onset: '鎮靜或躁動下降可能較早出現，但幻聽妄想等核心症狀通常要數天到數週才會慢慢改善。',
    commonSideEffects: ['僵硬', '坐立不安', '嗜睡', '姿勢性頭暈', '泌乳素相關變化'],
    seriousSideEffects: ['高燒與肌肉僵硬', '嚴重不自主動作', '心律不整', '明顯吞嚥或呼吸困難'],
    practicalTips: ['若出現手抖、僵硬或坐立難安要提早說', '不要因為症狀剛穩就自己停藥', '若有月經變化、泌乳或性功能困擾可直接討論'],
    missedDoseAdvice: '若是固定每天服用，發現漏吃時先確認距離下次服藥時間，不要自行大量補服。',
    discontinuationAdvice: '突然停藥會提高復發與再住院風險，若副作用困擾通常可先調劑量或換藥。',
    whenToCall: ['發燒合併僵硬', '嚴重不自主動作', '明顯復發前兆再次出現'],
    faq: [
      { question: '為什麼穩定了還要繼續吃？', answer: '穩定期持續治療能顯著降低復發風險，尤其停藥後短期內很容易再惡化。' },
      { question: '副作用是不是就只能忍？', answer: '不是，很多副作用都有調整方法，重點是盡早講。' },
    ],
    relatedDiagnosisIds: ['bipolar', 'schizophrenia'],
  },
  {
    id: 'antipsychotic-pine',
    slug: 'medication-antipsychotic-pine',
    name: '抗精神病藥：-pine 類',
    groupId: 'antipsychotics',
    groupLabel: '抗精神病藥',
    groupDescription: '先選抗精神病藥，再區分 -done、-pine、-piprazole 類等常見群組。',
    classLabel: 'Olanzapine / Quetiapine / Clozapine / Asenapine 等',
    shortSummary: '這一類較常見嗜睡、食慾與體重代謝問題，不同藥物之間差異也很大。',
    patientIntro: '-pine 類常見在躁期、思覺失調或晚間躁動中使用，有些藥偏鎮靜，有些需要特別注意體重、血糖與抽血監測。',
    indications: ['思覺失調症', '躁期', '失眠合併躁動', '治療阻抗個案'],
    onset: '嗜睡與鎮靜常比較快出現，核心精神症狀改善仍需要幾天到幾週。',
    commonSideEffects: ['嗜睡', '食慾增加', '體重上升', '口乾', '便秘'],
    seriousSideEffects: ['血糖血脂上升', '高燒與肌肉僵硬', '嚴重便秘或腸胃不通', '抽血異常監測問題'],
    practicalTips: ['開始用藥前後留意體重、腰圍與食慾', '若是 clozapine 類要依規定抽血', '白天太昏沉可和醫師討論服藥時間或換藥'],
    missedDoseAdvice: '若漏吃且不確定是否需要重新滴定，特別是高風險藥物，先和醫師或藥師確認。',
    discontinuationAdvice: '不要因為食慾或嗜睡困擾就直接停藥，很多時候可先透過時間調整、生活介入或換藥處理。',
    whenToCall: ['嗜睡到影響安全', '體重快速增加或血糖失控', '發燒、僵硬或便秘嚴重'],
    faq: [
      { question: '體重增加一定會發生嗎？', answer: '不一定，但這一類確實較常見，需要提早做飲食與活動調整。' },
      { question: '為什麼有些要一直抽血？', answer: '像 clozapine 需要監測白血球等安全性，這是藥物本身必要的追蹤。' },
    ],
    relatedDiagnosisIds: ['bipolar', 'schizophrenia', 'anxiety', 'insomnia'],
  },
  {
    id: 'antipsychotic-piprazole',
    slug: 'medication-antipsychotic-piprazole',
    name: '抗精神病藥：-piprazole 類',
    groupId: 'antipsychotics',
    groupLabel: '抗精神病藥',
    groupDescription: '先選抗精神病藥，再區分 -done、-pine、-piprazole 類等常見群組。',
    classLabel: 'Aripiprazole / Brexpiprazole / Cariprazine 等',
    shortSummary: '相對較不嗜睡、較不易增重，但更要注意坐立不安、失眠或焦躁。',
    patientIntro: '-piprazole 類常被拿來處理思覺失調、躁期，或作為部分情緒治療的增強策略；副作用型態常和 -pine 類不同。',
    indications: ['思覺失調症', '躁期', '情緒治療增強', '維持期治療'],
    onset: '躁動降低可能較早出現，穩定思考與情緒仍需要持續數天到數週觀察。',
    commonSideEffects: ['坐立不安', '失眠', '焦躁', '噁心', '頭暈'],
    seriousSideEffects: ['嚴重坐立不安', '衝動控制問題', '高燒與肌肉僵硬', '復發惡化'],
    practicalTips: ['若出現靜不下來、腿很想動，要盡快說', '若晚上越吃越睡不著，可討論服藥時間', '不是比較清醒就代表可以自行停藥'],
    missedDoseAdvice: '固定用藥漏吃時不要自己補雙倍，若是長效針劑或特殊劑型，更要按原本計畫回診處理。',
    discontinuationAdvice: '停藥太快仍會增加復發風險，尤其症狀剛穩時更不要自行測試可不可以停。',
    whenToCall: ['焦躁失眠快速惡化', '出現衝動消費或賭博等異常衝動', '明顯復發前兆再次出現'],
    faq: [
      { question: '是不是副作用比較少？', answer: '不是比較少，而是副作用型態不同，像坐立不安就要特別小心。' },
      { question: '為什麼我反而更睡不著？', answer: '這一類對部分人比較偏活化，如果服藥後更亢奮，要回診討論。' },
    ],
    relatedDiagnosisIds: ['bipolar', 'schizophrenia', 'depression'],
  },
  {
    id: 'mood-lithium',
    slug: 'medication-mood-lithium',
    name: '情緒穩定劑：Lithium',
    groupId: 'mood-stabilizers',
    groupLabel: '情緒穩定劑',
    groupDescription: '先選情緒穩定劑，再區分 Lithium、Depakine 或 Lamictal 等差異很大的藥物。',
    classLabel: 'Lithium carbonate',
    shortSummary: '對躁期與維持治療都很重要，但需要抽血監測濃度、腎功能與甲狀腺。',
    patientIntro: 'Lithium 是雙相情緒障礙的重要核心藥物之一，效果好，但安全範圍較窄，因此規律抽血與補水非常重要。',
    indications: ['雙相躁期', '雙相維持治療', '反覆情緒波動', '部分自殺風險較高個案'],
    onset: '起效通常需要數天到 1 到 2 週，血中濃度和臨床反應都要一起看。',
    commonSideEffects: ['手抖', '口渴', '頻尿', '腸胃不適', '體重變化'],
    seriousSideEffects: ['鋰鹽中毒', '嚴重脫水', '腎功能異常', '甲狀腺功能異常'],
    practicalTips: ['固定抽血時間與回診', '流汗、腹瀉、嘔吐或喝水太少時更要提高警覺', '不要自行亂加止痛藥或保健品'],
    missedDoseAdvice: '若忘記服藥不要自行補雙倍，尤其接近抽血或已漏超過一次時，先和醫療團隊確認。',
    discontinuationAdvice: 'Lithium 停得太快容易讓躁期或憂鬱期回來，也可能打亂原本穩定的情緒節律。',
    whenToCall: ['持續嘔吐腹瀉或脫水', '手抖、步態不穩或說話含糊', '抽血數值異常或明顯口渴頻尿'],
    faq: [
      { question: '為什麼一定要抽血？', answer: '因為 Lithium 有效範圍和中毒範圍靠得比較近，需要看濃度與身體代謝狀況。' },
      { question: '喝水有差嗎？', answer: '有，脫水會讓鋰鹽濃度上升，因此腹瀉、發燒或大量流汗時要特別小心。' },
    ],
    relatedDiagnosisIds: ['bipolar'],
  },
  {
    id: 'mood-valproate',
    slug: 'medication-mood-valproate',
    name: '情緒穩定劑：Depakine / Valproate',
    groupId: 'mood-stabilizers',
    groupLabel: '情緒穩定劑',
    groupDescription: '先選情緒穩定劑，再區分 Lithium、Depakine 或 Lamictal 等差異很大的藥物。',
    classLabel: 'Valproate / Divalproex / Depakine',
    shortSummary: '常用在躁期與情緒波動控制，常見要注意肝功能、體重與懷孕相關風險。',
    patientIntro: 'Valproate 類常用於躁期、情緒不穩或衝動躁動，起效可比 Lamotrigine 快，但監測重點完全不同。',
    indications: ['雙相躁期', '情緒波動控制', '衝動躁動', '混合型發作'],
    onset: '通常數天到 1 到 2 週可看到躁動與情緒高昂慢慢下降。',
    commonSideEffects: ['想睡', '腸胃不適', '體重增加', '手抖', '落髮'],
    seriousSideEffects: ['肝功能異常', '胰臟炎', '血小板異常', '懷孕相關風險'],
    practicalTips: ['回診時帶上最近體重與月經或生育規畫資訊', '若有腹痛、黃疸或容易瘀青要早點說', '育齡個案需提早討論避孕與懷孕計畫'],
    missedDoseAdvice: '漏吃時不要自己補雙倍，若是緩釋劑型或已經漏多次，更要先確認再處理。',
    discontinuationAdvice: 'Valproate 也不適合突然停，尤其在躁期剛穩定時，快速停藥很容易反彈。',
    whenToCall: ['腹痛或持續嘔吐', '黃疸、深色尿', '皮下出血或月經異常明顯'],
    faq: [
      { question: '為什麼醫師一直問懷孕計畫？', answer: '因為 Valproate 對胎兒風險較高，需要很早就把生育規畫納入考量。' },
      { question: '吃了變胖怎麼辦？', answer: '這一類確實可能影響體重，越早介入飲食與活動調整越有幫助。' },
    ],
    relatedDiagnosisIds: ['bipolar'],
  },
  {
    id: 'mood-lamotrigine',
    slug: 'medication-mood-lamotrigine',
    name: '情緒穩定劑：Lamictal / Lamotrigine',
    groupId: 'mood-stabilizers',
    groupLabel: '情緒穩定劑',
    groupDescription: '先選情緒穩定劑，再區分 Lithium、Depakine 或 Lamictal 等差異很大的藥物。',
    classLabel: 'Lamotrigine / Lamictal',
    shortSummary: '較常用在雙相憂鬱與維持期，起效慢，最重要是按計畫慢慢加量並警覺皮疹。',
    patientIntro: 'Lamotrigine 常用在雙相憂鬱或維持期，特色是需要慢慢加量，最需要小心的是皮疹與過快加藥。',
    indications: ['雙相憂鬱期', '雙相維持治療', '情緒低落反覆'],
    onset: '因為需要漸進加量，通常不會很快見效，常要數週以上才會穩定看出效果。',
    commonSideEffects: ['頭暈', '頭痛', '噁心', '睡眠改變', '輕微皮疹'],
    seriousSideEffects: ['嚴重皮膚過敏', '發燒合併皮疹', '黏膜潰瘍', '肝功能異常'],
    practicalTips: ['嚴格照加量表走，不要自己追快', '若中斷一段時間再吃，可能需要重新慢慢加回來', '一旦皮疹快速擴大要立刻聯絡醫師'],
    missedDoseAdvice: '若漏藥超過幾天，可能不能直接回到原劑量，最好先聯絡醫師確認。',
    discontinuationAdvice: 'Lamotrigine 不是沒副作用就可以隨便停，停藥過程仍要避免情緒再度失穩。',
    whenToCall: ['皮疹快速擴大', '發燒、喉嚨痛或嘴破合併皮疹', '情緒低落明顯惡化'],
    faq: [
      { question: '為什麼這顆加藥這麼慢？', answer: '因為加太快會提高嚴重皮膚過敏風險，所以需要慢慢往上調。' },
      { question: '幾天沒吃可以直接接回來嗎？', answer: '不一定，停太久後常需要重新滴定，不能自己硬接回原本劑量。' },
    ],
    relatedDiagnosisIds: ['bipolar'],
  },
  {
    id: 'adhd-stimulant',
    slug: 'medication-adhd-stimulant',
    name: 'ADHD 藥物：刺激劑',
    groupId: 'adhd-medications',
    groupLabel: 'ADHD 常用藥',
    groupDescription: '先選 ADHD 藥物，再區分刺激劑、Atomoxetine 或其他非刺激劑。',
    classLabel: 'Methylphenidate 類',
    shortSummary: '常是效果最快的一群，對專注與衝動有幫助，但要注意食慾、心悸與睡眠。',
    patientIntro: '刺激劑常在當天就能感受到效果，因此很適合一邊調藥、一邊觀察專注、食慾與睡眠的改變。',
    indications: ['兒童與成人 ADHD', '專注力不足', '衝動控制困難'],
    onset: '短效或長效劑型通常都能在當天感受到差別，但穩定找到合適劑量仍需要幾次回診。',
    commonSideEffects: ['食慾下降', '心悸', '睡眠延後', '口乾', '情緒煩躁'],
    seriousSideEffects: ['胸痛', '明顯情緒惡化', '體重快速下降', '抽動明顯加劇'],
    practicalTips: ['記錄藥效開始與結束時間', '中午與晚上觀察食慾和情緒回彈', '通常不建議太晚補吃'],
    missedDoseAdvice: '下午或晚上通常不建議補吃，以免影響睡眠；若常忘記服藥，可和醫師討論劑型或提醒方式。',
    discontinuationAdvice: '若副作用明顯應回診調整，不要自行頻繁停停吃吃，否則很難判斷真正適合的劑量。',
    whenToCall: ['胸痛或明顯心悸', '食慾下降到影響體重', '情緒暴躁或哭鬧明顯增加'],
    faq: [
      { question: '吃藥會不會改變個性？', answer: '目標是減少分心與衝動，不是把人變得沒有特色。' },
      { question: '假日需要停藥嗎？', answer: '要看功能需求與副作用，不是每個人都適合固定停藥日。' },
    ],
    relatedDiagnosisIds: ['adhd'],
  },
  {
    id: 'adhd-atomoxetine',
    slug: 'medication-adhd-atomoxetine',
    name: 'ADHD 藥物：Atomoxetine',
    groupId: 'adhd-medications',
    groupLabel: 'ADHD 常用藥',
    groupDescription: '先選 ADHD 藥物，再區分刺激劑、Atomoxetine 或其他非刺激劑。',
    classLabel: 'Atomoxetine',
    shortSummary: '屬於非刺激劑，起效比刺激劑慢，但對部分焦慮合併 ADHD 個案較適合。',
    patientIntro: 'Atomoxetine 不是當天就見效的藥，通常需要數週累積，因此規律服用和耐心觀察比馬上追求感覺更重要。',
    indications: ['兒童與成人 ADHD', '焦慮合併 ADHD', '刺激劑不適合個案'],
    onset: '多半要 2 到 6 週才會慢慢看出差異，初期可能先出現腸胃不適或疲倦。',
    commonSideEffects: ['噁心', '食慾下降', '頭暈', '疲倦', '心悸'],
    seriousSideEffects: ['明顯情緒惡化', '自傷想法增加', '肝功能異常', '尿滯留'],
    practicalTips: ['至少連續觀察幾週再評估效果', '可記錄上午與傍晚專注變化', '若有明顯黃疸、深色尿或情緒惡化要提早回診'],
    missedDoseAdvice: '想起來時若還早可補吃，若已接近睡前則先跳過，不要補雙倍。',
    discontinuationAdvice: '雖然不是刺激劑，也不建議自行忽停忽吃，以免效果判讀混亂。',
    whenToCall: ['情緒明顯變差', '黃疸或深色尿', '心悸明顯或排尿困難'],
    faq: [
      { question: '為什麼這顆比刺激劑慢？', answer: '因為機轉不同，需要時間累積，不是沒效，而是評估節奏不同。' },
      { question: '如果前幾天沒感覺要不要換藥？', answer: '通常太早，這類藥需要給足時間才能公平評估。' },
    ],
    relatedDiagnosisIds: ['adhd'],
  },
  {
    id: 'adhd-alpha2',
    slug: 'medication-adhd-alpha2',
    name: 'ADHD 藥物：Alpha-2 類',
    groupId: 'adhd-medications',
    groupLabel: 'ADHD 常用藥',
    groupDescription: '先選 ADHD 藥物，再區分刺激劑、Atomoxetine 或其他非刺激劑。',
    classLabel: 'Guanfacine / Clonidine',
    shortSummary: '常用在衝動、情緒易爆或晚間難降速的情況，要注意嗜睡與血壓。',
    patientIntro: 'Alpha-2 類常用於衝動、情緒易爆、睡前難降速或抽動合併 ADHD 的個案，和刺激劑的觀察重點不太一樣。',
    indications: ['衝動控制困難', '情緒易爆', '抽動合併 ADHD', '晚間難降速'],
    onset: '有些人幾天內就覺得比較安定，但找到合適劑量仍需要逐步調整。',
    commonSideEffects: ['嗜睡', '頭暈', '血壓偏低', '口乾', '便秘'],
    seriousSideEffects: ['昏厥', '心跳過慢', '明顯無力', '突然停藥後血壓反彈'],
    practicalTips: ['剛開始或加量時注意起立頭暈', '若白天太想睡，可討論服藥時間', '不要突然停藥，尤其已吃一段時間者'],
    missedDoseAdvice: '若已接近下一次服藥時間就先跳過，不要補雙倍，長期使用者更不要突然整天沒吃。',
    discontinuationAdvice: '這類藥物停太快可能出現血壓反彈或躁動，需按計畫慢慢退。',
    whenToCall: ['昏厥或明顯頭暈', '心跳過慢', '停藥後突然躁動或血壓不穩'],
    faq: [
      { question: '這顆為什麼會想睡？', answer: '它本來就可能讓身體比較降速，對部分人反而是治療目標的一部分。' },
      { question: '是不是比刺激劑弱？', answer: '不是強弱問題，而是適合處理的症狀型態不同。' },
    ],
    relatedDiagnosisIds: ['adhd'],
  },
]

const modules: CareModule[] = [
  {
    id: 'sleep-rhythm',
    slug: 'module-sleep-rhythm',
    kind: 'lifestyle',
    title: '睡眠節律重整',
    summary: '醫師端只看固定起床、減少補眠與建立晚間降速流程。',
    patientSummary: '睡眠重整的核心不是逼自己早點睡，而是每天給身體固定的起床與放鬆訊號，讓大腦重新學會在對的時間睡。',
    bullets: ['固定起床時間比固定睡著時間更重要', '睡不著時不要一直躺著硬撐', '白天活動量與日照會影響夜間睡意'],
    practicalSteps: ['先固定一個每天都做得到的起床時間，假日也不要差太多', '若躺床 20 到 30 分鐘還睡不著，先離床做安靜無聊的活動', '晚間 1 小時開始關閉強光、工作與滑手機刺激'],
  },
  {
    id: 'stress-regulation',
    slug: 'module-stress-regulation',
    kind: 'counseling',
    title: '壓力與焦慮降速',
    summary: '醫師端只看呼吸、肌肉放鬆與刺激減量三件事。',
    patientSummary: '焦慮下降通常不是靠意志力壓住，而是讓身體從警報模式慢慢退回可思考的狀態。',
    bullets: ['先處理身體，再處理想法', '放鬆技巧要平常練，發作時才叫得出來', '咖啡因、熬夜與過度刺激會放大焦慮'],
    practicalSteps: ['每天固定 5 分鐘做慢呼吸或漸進式肌肉放鬆，不要等發作才開始', '焦慮衝上來時先延長吐氣，再決定下一步', '把最常觸發焦慮的時段、地點與想法寫下來，回診時一起看'],
  },
  {
    id: 'panic-grounding',
    slug: 'module-panic-grounding',
    kind: 'counseling',
    title: '恐慌當下的穩定法',
    summary: '醫師端只看 grounding、慢吐氣、延後逃離。',
    patientSummary: '恐慌發作時，大腦會一直把身體感覺解讀成危險。穩定法的目標不是立刻把感覺消掉，而是把自己從失控拉回可撐住的狀態。',
    bullets: ['先把注意力拉回外界', '吐氣放慢比拼命吸氣更重要', '不要每次都立刻逃離，否則大腦會更認定那裡危險'],
    practicalSteps: ['用 5-4-3-2-1 方法點出看到、摸到、聽到的事物，讓注意力離開身體警報', '吐氣時間比吸氣長，例如吸 4 拍、吐 6 拍', '若可以，先在原地多待 1 到 3 分鐘再離開，慢慢降低逃離反射'],
  },
  {
    id: 'activity-activation',
    slug: 'module-activity-activation',
    kind: 'counseling',
    title: '低潮時的行動啟動',
    summary: '醫師端只看小任務、固定節奏與完成感回收。',
    patientSummary: '在憂鬱低潮時，等有動力才開始通常會卡更久。比較有用的方法是先做很小、做得到的事，用行動慢慢把能量拉回來。',
    bullets: ['把目標縮小到現在做得到的程度', '先做再評價，不要先等感覺變好', '完成感要刻意記下來'],
    practicalSteps: ['每天排 1 到 2 個 10 分鐘就能完成的小任務，例如洗澡、走出門、回一封訊息', '把任務切成起步版，例如只整理桌面 3 分鐘', '做完後記一筆「我有做到」，讓大腦慢慢恢復完成經驗'],
  },
  {
    id: 'family-communication',
    slug: 'module-family-communication',
    kind: 'counseling',
    title: '家屬溝通與危機辨識',
    summary: '醫師端只看主要聯絡人、前兆清單與危機處理分工。',
    patientSummary: '家屬參與最有幫助的地方，不是一直提醒要加油，而是知道什麼是前兆、什麼時候該協助就醫，以及平常怎麼支持比較不容易起衝突。',
    bullets: ['先約定一位主要聯絡人', '前兆要寫成可觀察的行為', '危機時先處理安全，再談道理'],
    practicalSteps: ['一起列出 3 到 5 個最常見的前兆，例如睡很少、話變多、拒絕出門、開始藏藥', '把求助窗口、常用醫院與回診時間寫在家人找得到的地方', '溝通時盡量用觀察句，例如「你這三天都沒睡」而不是「你又發作了」'],
  },
  {
    id: 'therapy-engagement',
    slug: 'module-therapy-engagement',
    kind: 'counseling',
    title: '心理治療與追蹤參與',
    summary: '醫師端只看回診目標、症狀紀錄與治療任務。',
    patientSummary: '回診與心理治療最有幫助的時候，不是臨場想到什麼說什麼，而是把最近最困擾的事、誘發情境和副作用先整理好。',
    bullets: ['每次回診帶一到兩個最想解決的問題', '症狀與副作用要一起記', '治療要有短期目標才知道方向'],
    practicalSteps: ['回診前先寫下最近一週最困擾的 2 件事與最想問的 1 個問題', '用手機記事記錄睡眠、情緒、藥物副作用與特殊事件', '若開始心理治療，先和治療師約定一個 4 到 8 週的具體目標'],
  },
  {
    id: 'return-to-work',
    slug: 'module-return-to-work',
    kind: 'lifestyle',
    title: '復學復工節奏',
    summary: '醫師端只看先求穩定、分段回歸與任務拆解。',
    patientSummary: '復學復工最怕一下回到滿載又快速崩掉。比起衝刺，更重要的是設計一個可持續的回歸節奏。',
    bullets: ['先恢復穩定出現，再追求表現', '任務量要分段上升', '事前溝通比臨時硬撐更有幫助'],
    practicalSteps: ['先從固定時段、半天班或單一責任開始，不急著一次回到全部工作量', '把一天最重要的任務控制在 1 到 3 件', '和學校、主管或家人先講好哪些項目可調整、哪些是底線'],
  },
  {
    id: 'substance-reduction',
    slug: 'module-substance-reduction',
    kind: 'lifestyle',
    title: '酒精與物質減量',
    summary: '醫師端只看酒精、娛樂性藥物與咖啡因先辨識再減量。',
    patientSummary: '酒精、娛樂性藥物與過量咖啡因很容易讓睡眠、焦慮、情緒波動與藥物副作用一起變糟，因此減量不是附帶建議，而是治療的一部分。',
    bullets: ['先找出最常使用的情境', '先減少危險搭配', '誠實回報比隱瞞更能保護安全'],
    practicalSteps: ['先記一週在什麼時間、什麼情緒下最容易喝酒或使用物質', '第一步先避免和鎮靜安眠藥一起使用', '若自己很難減，回診時直接講實際量，不需要先等完全戒掉才說'],
  },
  {
    id: 'medication-adherence',
    slug: 'module-medication-adherence',
    kind: 'lifestyle',
    title: '規律服藥與副作用回報',
    summary: '醫師端只看提醒系統、漏藥處理與副作用提早回報。',
    patientSummary: '很多治療卡關不是因為藥沒效，而是吃吃停停、漏藥後亂補，或副作用撐太久沒說。規律與回報本身就是治療成效的一部分。',
    bullets: ['用系統提醒，不要只靠記憶', '漏藥不要自己亂補', '副作用早講通常比硬撐更有選項'],
    practicalSteps: ['把藥盒、鬧鐘、手機提醒或家人提醒固定成一套流程', '一旦漏藥，先看醫囑或藥袋，不確定時不要補雙倍', '把副作用記成具體描述，例如「下午 2 點很昏」而不是只寫不舒服'],
  },
  {
    id: 'relapse-signatures',
    slug: 'module-relapse-signatures',
    kind: 'counseling',
    title: '復發前兆辨識',
    summary: '醫師端只看個人前兆、提早處理與求助門檻。',
    patientSummary: '很多復發不是完全沒有預兆，而是前兆出現時沒有被認出來。越早發現自己的固定模式，越有機會在惡化前就先處理。',
    bullets: ['前兆通常是個人固定模式', '越早處理越不用等到失控', '要先約定什麼情況算需要求助'],
    practicalSteps: ['回想前一次惡化前 1 到 2 週，列出最先出現的 3 個變化', '把前兆分成黃色警訊與紅色警訊，決定各自要做什麼', '提前和家人或朋友約定，當你出現某些行為時可以怎麼提醒或協助就醫'],
  },
  {
    id: 'task-structuring',
    slug: 'module-task-structuring',
    kind: 'lifestyle',
    title: '注意力與任務拆解',
    summary: '醫師端只看外部提醒、短工時段與收尾流程。',
    patientSummary: '對注意力困難的人來說，問題常不是不知道要做什麼，而是開始不了、切不回來、收不乾淨。任務拆解是把大腦負擔外掛出去。',
    bullets: ['先定開始點，再定完成點', '時間短一點比想得很完整更有用', '外部提醒比只靠腦內記憶穩定'],
    practicalSteps: ['每個任務先寫成「開始動作 + 完成條件」，例如打開檔案並完成第一段', '一次只工作 10 到 25 分鐘，中間安排明確休息', '每次收工前花 3 分鐘把下一步寫下來，降低下次啟動門檻'],
  },
  {
    id: 'screen-boundaries',
    slug: 'module-screen-boundaries',
    kind: 'lifestyle',
    title: '晚間螢幕與刺激管理',
    summary: '醫師端只看晚間降光、停止追劇與睡前轉場。',
    patientSummary: '很多人不是不累，而是睡前一直被藍光、資訊與情緒刺激拉住。晚間邊界管理是在幫大腦切換到可以睡的模式。',
    bullets: ['睡前需要轉場，不是直接從工作跳進睡眠', '藍光和情緒刺激都會拉高警醒', '邊界要設在睡前 30 到 60 分鐘'],
    practicalSteps: ['先選一個固定的「下線時間」，到點就停止回工作訊息與滑短影音', '把手機充電位置移出床邊，減少半夜反射性拿起來', '睡前改做重複、低刺激的活動，例如泡澡、拉筋、紙本閱讀或整理明天待辦'],
  },
]

export const defaultContentPack: ContentPack = {
  diagnoses,
  medications,
  modules,
  template: {
    id: 'default-a4-template',
    name: '精神科個人化衛教單',
    sectionOrder: ['diagnosis', 'treatment', 'medication', 'modules', 'urgent', 'qr'],
    noteLimit: 60,
  },
}

export const contentPack = defaultContentPack

export function cloneContentPack(content: ContentPack = defaultContentPack): ContentPack {
  return JSON.parse(JSON.stringify(content)) as ContentPack
}

export function createContentMaps(content: ContentPack) {
  return {
    diagnosisMap: new Map(content.diagnoses.map((diagnosis) => [diagnosis.id, diagnosis])),
    medicationMap: new Map(content.medications.map((medication) => [medication.id, medication])),
    moduleMap: new Map(content.modules.map((module) => [module.id, module])),
  }
}

export function getTopicBySlug(content: ContentPack, slug: string) {
  const diagnosis = content.diagnoses.find((item) => item.slug === slug)
  if (diagnosis) {
    return { kind: 'diagnosis' as const, topic: diagnosis }
  }

  const medication = content.medications.find((item) => item.slug === slug)
  if (medication) {
    return { kind: 'medication' as const, topic: medication }
  }

  const module = content.modules.find((item) => item.slug === slug)
  if (module) {
    return { kind: 'module' as const, topic: module }
  }

  return null
}

export function getRelatedMedications(content: ContentPack, ids: string[]) {
  const { medicationMap } = createContentMaps(content)

  return ids.map((id) => medicationMap.get(id)).filter(Boolean) as MedicationTopic[]
}

export function getRelatedModules(content: ContentPack, ids: string[]) {
  const { moduleMap } = createContentMaps(content)

  return ids.map((id) => moduleMap.get(id)).filter(Boolean) as CareModule[]
}
